"""
youtube_uploader.py — Uploads main video and YouTube Short using YouTube Data API v3.

Authentication:
  On Railway: reads YOUTUBE_TOKEN_B64 env var, decodes it to token.pickle at startup.
  Locally: uses token.pickle generated by auth_setup.py.
  Token is refreshed automatically when expired.
"""

import base64
import os
import pickle
import logging
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
from google.auth.transport.requests import Request
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

load_dotenv()

logger = logging.getLogger(__name__)

SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]
TOKEN_FILE = Path(__file__).parent / "token.pickle"
SECRETS_FILE = Path(__file__).parent / "client_secrets.json"
CATEGORY_ID = "10"  # Music


def _restore_token_from_env() -> None:
    """
    If YOUTUBE_TOKEN_B64 is set (Railway), decode it and write token.pickle to disk.
    This runs once at import time so the rest of the module works unchanged.
    """
    b64 = os.environ.get("YOUTUBE_TOKEN_B64")
    if not b64:
        return
    if TOKEN_FILE.exists():
        return  # already on disk (e.g. local dev)
    try:
        TOKEN_FILE.write_bytes(base64.b64decode(b64))
        logger.info("token.pickle restored from YOUTUBE_TOKEN_B64")
    except Exception as exc:
        raise RuntimeError(f"Failed to decode YOUTUBE_TOKEN_B64 into token.pickle: {exc}") from exc


# Restore token on module load so it's available before any function is called
_restore_token_from_env()


def _get_youtube_client():
    creds = None

    if TOKEN_FILE.exists():
        with open(TOKEN_FILE, "rb") as f:
            creds = pickle.load(f)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not SECRETS_FILE.exists():
                raise FileNotFoundError(
                    "No valid credentials found. "
                    "Set YOUTUBE_TOKEN_B64 (Railway) or run auth_setup.py locally."
                )
            flow = InstalledAppFlow.from_client_secrets_file(str(SECRETS_FILE), SCOPES)
            creds = flow.run_local_server(port=0)

        with open(TOKEN_FILE, "wb") as f:
            pickle.dump(creds, f)

    return build("youtube", "v3", credentials=creds)


def _upload_single_video(
    youtube,
    video_path: str,
    title: str,
    description: str,
    tags: list[str],
    is_short: bool = False,
    short_hook: Optional[str] = None,
) -> str:
    """Upload one video and return the YouTube video ID."""
    privacy = os.environ.get("YT_PRIVACY", "private")

    if is_short:
        upload_title = f"#Shorts {title[:55]}" if len(title) <= 55 else f"#Shorts {title[:52]}..."
        upload_description = f"{short_hook or title}\n\n#Shorts #KidsShorts #HappyMelodyKids"
        upload_tags = tags[:5] + ["Shorts", "KidsShorts", "HappyMelodyKids"]
    else:
        upload_title = title[:100]
        upload_description = description
        upload_tags = tags

    body = {
        "snippet": {
            "title": upload_title,
            "description": upload_description,
            "tags": upload_tags,
            "categoryId": CATEGORY_ID,
            "defaultLanguage": "en",
        },
        "status": {
            "privacyStatus": privacy,
            "selfDeclaredMadeForKids": True,
        },
    }

    media = MediaFileUpload(video_path, mimetype="video/mp4", resumable=True, chunksize=1024 * 1024 * 5)
    request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)

    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            logger.debug("Upload progress: %d%%", int(status.progress() * 100))

    video_id = response["id"]
    logger.info("Uploaded %s → https://youtu.be/%s", "Short" if is_short else "main video", video_id)
    return video_id


def upload_videos(
    main_video_path: str,
    short_video_path: str,
    title: str,
    description: str,
    tags: list[str],
    short_hook: str,
) -> dict:
    """Upload main video + Short. Returns dict with main_id and short_id."""
    youtube = _get_youtube_client()

    main_id = _upload_single_video(
        youtube,
        video_path=main_video_path,
        title=title,
        description=description,
        tags=tags,
        is_short=False,
    )

    short_id = _upload_single_video(
        youtube,
        video_path=short_video_path,
        title=title,
        description=description,
        tags=tags,
        is_short=True,
        short_hook=short_hook,
    )

    return {"main_id": main_id, "short_id": short_id}
